template: true
valuesFilePath: values.yml  # relative path for values.yml
 
 
resources:
  - name: {{ Values.GitRepo.name }}
    type: GitRepo
    configuration:
      gitProvider: {{ Values.GitRepo.gitProvider }}
      path: {{ Values.GitRepo.path }}
      branches:
        include: {{ Values.GitRepo.branches.include }}
 
  - name: {{ Values.Image.name }}
    type: Image
    configuration:
      registry: {{ Values.artifactoryIntegration }}
      sourceRepository: {{ Values.Image.sourceRepository }}
      imageName: {{ Values.DockerBuild.dockerImageName }}
      imageTag: '1'
      autoPull: true
 
pipelines:
  - name: {{ Values.Pipeline.name }}
    steps:
      - name: {{ Values.DockerBuild.name }}
        type: DockerBuild
        configuration:
          affinityGroup: DockerBuildAndPush
          dockerFileLocation: {{ Values.DockerBuild.dockerFileLocation }}
          dockerFileName: {{ Values.DockerBuild.dockerFileName }}
          dockerImageName: {{ Values.DockerBuild.dockerImageName }}
          dockerImageTag: {{ Values.DockerBuild.dockerImageTag }}
          inputResources:
            - name: {{ Values.GitRepo.name }}
          integrations:
            - name: {{ Values.artifactoryIntegration }}
 
      - name: {{ Values.DockerPush.name }}
        type: DockerPush
        configuration:
          affinityGroup: DockerBuildAndPush
          targetRepository: {{ Values.DockerPush.targetRepository }}
          integrations:
            - name: {{ Values.artifactoryIntegration }}
          inputSteps:
            - name: {{ Values.DockerBuild.name }}
          outputResources:
            - name: {{ Values.Image.name }}
